version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - app
    depends_on:
      - server

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:465
      - GF_SMTP_USER=hamzachebildevops@gmail.com
      - GF_SMTP_PASSWORD=devops@123
    networks:
      - app
    depends_on:
      - prometheus

  server:
    image: hamzachebil/devops-project
#    build:
#      context: ./server
    ports:
      - 8000:8000
    networks:
      - app
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: '10s'

volumes:
  prometheus-data:
  grafana_data:

networks:
  app:
