global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'app_metrics'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['server:8000']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
